language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jameshamlett/docker-react -f Dockerfile.dev .

script:
  # - docker run -e CI=true jameshamlett/docker-react npm run test
  - docker run jameshamlett/docker-react npm run test -- --coverage