language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jameshamlett/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jameshamlett/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-1-348060775589"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
